### ISSUE TITLE
area

### ISSUE THREAD

**Issue by ceccorsi** [Nikhil-Adithyan/Customer-Segmentation-with-K-Means#1]
please, help me:

area = df.DebtIncomeRatio **2

...s = area.....

but i got:

"s must be a scalar, or the same size as x and y"

**Comment by Nikhil-Adithyan** [comment]
Don't worry, just a tiny change in processing the data. As the 'Defaulted' column contains more 'NaN' values, we have to process them using the 'nan_to_num' method provided by the NumPy package. Hope this piece of code would resolve your problem and produce the desired output. Cheers.
```
df['Defaulted'] = np.nan_to_num(df['Defaulted'])
area = df.DebtIncomeRatio**2

sb.scatterplot('Age', 'Income', 
               data = df, 
               hue = 'Defaulted', 
               s = area, 
               palette = 'spring', 
               alpha = 0.6, 
               edgecolor = 'white')
plt.title('YEARS EMPLOYED / INCOME', 
          fontsize = 18)
plt.xlabel('Years Employed', 
           fontsize = 16)
plt.ylabel('Income', 
           fontsize = 16)
plt.xticks(fontsize = 14)
plt.yticks(fontsize = 14)
plt.legend(loc = 'upper left', fontsize = 14, title = 'Defaulted')

plt.show()
```

**Comment by ceccorsi** [comment]
GREAT!!! Thanks a lot!!!

Em ter., 24 de nov. de 2020 às 12:44, Nikhil Adithyan <
notifications@github.com> escreveu:
